  spring:
    application:
      name: gestion-usuarios

    datasource:
      url: jdbc:h2:mem:gestiondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:

    h2:
      console:
        enabled: true
        path: /h2-console

    jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    sql:
      init:
        mode: always
        encoding: UTF-8

  management:
    endpoints:
      web:
        exposure:
          include: health,info
