apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gestion-usuarios.fullname" . }}
  labels:
    {{- include "gestion-usuarios.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /usuario(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "gestion-usuarios.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
