# Default values for gestion-usuarios.

replicaCount: 1

image:
  repository: acmeneses496/gestion-usuarios
  pullPolicy: IfNotPresent
  tag: "6cbf814"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# --- Servicio interno expuesto dentro del cluster ---
service:
  type: ClusterIP   # 👈 Importante: usamos Ingress, no se necesita LoadBalancer
  port: 80          # Puerto expuesto dentro del cluster
  targetPort: 8080  # Puerto donde corre tu app dentro del contenedor
  protocol: TCP
  labels:
    app: gestion-usuarios

# --- Ingress configuration ---
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  tls: []  # Puedes agregar configuración TLS si luego usas HTTPS

# --- HTTPRoute deshabilitado ---
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}
# Ejemplo (si quieres limitar recursos):
# limits:
#   cpu: 200m
#   memory: 512Mi
# requests:
#   cpu: 100m
#   memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}



