# Default values for gestion-usuarios.

replicaCount: 2

image:
  repository: acmeneses496/gestion-usuarios
  pullPolicy: IfNotPresent
  tag: ca9ad13

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# --- Servicio interno expuesto dentro del cluster ---
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP
  labels:
    app: gestion-usuarios

# --- Ingress configuration ---
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  tls: []  # Puedes agregar configuración TLS si luego usas HTTPS

# --- HTTPRoute deshabilitado ---
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}


